### PR TITLE
perf: remove unused properties from radix

### PR DESCRIPTION
**Pull request by H4ad**
There is currently no reason for `radix` to have an `id` or `parent` property, so can we remove it?

This breaks a test in `dataset.test.ts`, but breaks the order of the `snapshot`, from what I can see the documents are just being returned in a different order than expected.

### CODE REVIEW

**Comment by micheleriva** [comment]
@H4ad tests are not passing, but I can't understand how this refactor could affect pagination results

**Comment by H4ad** [comment]
@micheleriva Probably is due the default sort is not stable: https://medium.com/@fsufitch/is-javascript-array-sort-stable-46b90822543f

**Comment by micheleriva** [comment]
@allevo any thoughts here?

**Comment by allevo** [comment]
I'm not worried about it. The sorting feature has a dedicated test suite, so it is preserved.

@H4ad  could you fix the test suite?

**Review by micheleriva — APPROVED** [review]
LGTM

**Pull request merged**
