### PR TITLE
Chore: upgrade tap to 18.6.1

### PR DESCRIPTION
**Pull request by debiff**
/claim https://github.com/oramasearch/orama/issues/578

This PR upgrades the test library `Tap` to `18.6.1`.
In the meantime also the library `@types/node` was upgraded to `20.9.0`.

As reference:
- here is the guide for upgrading from version 16 to version 18 of Tap: https://node-tap.org/upgrading-from-16/
- here is an answer to an issue that explains how to set the parameters in the config (not really clear from the doc) https://github.com/tapjs/tapjs/issues/969#issuecomment-1793120652

### CODE REVIEW

**Comment by micheleriva** [comment]
Hi @debiff,
I fear the tests are not passing in CI

**Comment by debiff** [comment]
> Hi @debiff, I fear the tests are not passing in CI

Sorry, I'll check asap

**Comment by debiff** [comment]
@micheleriva also executed on the fork's CI and now it seems to work. 
Let me know ( I don't think there are differences in the config of my fork, but just in case) :)

**Comment by micheleriva** [comment]
Thank you so much for the effort. We merged #581 since your solutions are both good, but #581 had priority since it was opened earlier :(

**Comment by debiff** [comment]
@micheleriva Never mind! It was good for me to try to contribute to an open-source project to look at the logic! ;)

What do you think about avoiding initially the reward at least for the good first issues? I think that it allows people who want to start contributing to work on it without the pressure of people who want the reward (just take it as food for thought).
Bye :)

**Pull request closed without merging**
