### PR TITLE
fix: nextra plugin - router ready check

### LINKED ISSUE #396: Orama Nextra | Plugin | NextRouter was not mounted
### Description

After using the installation guide, https://docs.oramasearch.com/plugins/plugin-nextra, and followed all the instruction I receive this error:

```
Server Error
Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
This error happened while generating the page. Any console logs will be displayed in the terminal window.
```
### Step to reproduce

1. Add the import and component in `theme.config.jsx`
2. save and run `yarn dev`
3. open localhost:3000
4. see the error

### Expected behavior
Expected is the right working as the same search (flexsearch) as default

### Screenshots
NextRouter was not mounted

**Desktop (please complete the following information):**
 - OS: macOS Ventura Versione 13.0 (22A380)
 - Browser: Chrome (Versione 113.0.5672.126 (Build ufficiale) (arm64))

### PR DESCRIPTION
**Pull request by ilteoood**
fix #396
/claim #396

### CODE REVIEW

**Comment by micheleriva** [comment]
Thanks @ilteoood! Will review and test this early next week

**Review by micheleriva — APPROVED** [review]
@ilteoood looks good to me. I'll merge this and ask @scasolari to test it. If everything goes through, I'll grant you the bounty via Algora 🙂

**Comment by ilteoood** [comment]
@micheleriva don't worry, thank you for your trust 🙏

**Comment by scasolari** [comment]
Hi guys, tested and  it's works, amazing! @micheleriva @ilteoood

**Pull request merged**
