### PR TITLE
fix: usage of `a deprecated Node.js version` in CI

### LINKED ISSUE #840: `turbo.yml` uses actions that `use a deprecated Node.js version`
[`turbo.yml` uses actions that `use a deprecated Node.js version`](https://github.com/oramasearch/orama/actions/runs/11728289311).

### PR DESCRIPTION
**Pull request by hamirmahal**
Fixes #840

### CODE REVIEW

**Comment by hamirmahal** [comment]
# Without this change

Screenshot from 2024-11-08 08-21-42

**Comment by hamirmahal** [comment]
# With this change

image

**Review by hamirmahal — COMMENTED** [review]
`v4` is the latest major version, at the time of this pull request's creation, of all the actions updated here.

**Comment by micheleriva** [comment]
Thank you @hamirmahal !

**Comment by hamirmahal** [comment]
You're welcome @micheleriva!

**Review by micheleriva — APPROVED** [review]

**Pull request merged**
