### PR TITLE
created Korean stop-words file

### PR DESCRIPTION
**Pull request by tk-425**
Hello Lyra Team!

I got the list of Korean stop-words from [https://www.ranks.nl/stopwords/korean](url) and updated two `index.ts` files from the `tokenizer` and `stop-words` folders also updated `languages.ts` from the `tokenizer` folder as well. 
I tested it out by modifying the `node_module` source folder, and it seems to be working correctly.

`lyrademo.js`
```javascript
import { create, insert, search } from "@lyrasearch/lyra";

const db = create({
  schema: {
    author: "string",
    quote: "string",
  },
  defaultLanguage: "korean"
});

// **1
insert(db, {
  quote:
    "우와, 와 안녕하세요. 반갑습니다.",    // Woah, wow hello nice to meet you
  author: "리라",    // Lyra
});

// **2
insert(db, {
  quote:
    "리라와 리바",    // Lyra and Riva
  author: "리바",    // Riva
});

// **3
insert(db, {
  quote:
    "Hello World",
  author: "미셸 리바",    // Michele Riva
});

// #1
let searchResult = search(db, {
  term: "서치엔진에 대하여",    // about search engine
  properties: ["quote"],
});

console.log(searchResult);

// #2
searchResult = search(db, {
  term: "안녕하세요",    // hello
  properties: ["quote"],
});

console.log(searchResult);

// #3
searchResult = search(db, {
  term: "반갑",    // this word is the first two characters from 반갑습니다 (nice to meet you)
  properties: ["quote"],
});

console.log(searchResult);

// #4
searchResult = search(db, {
  term: "와",   // wow or and
  properties: ["quote"],
});

console.log(searchResult);

// #5
searchResult = search(db, {
  term: "대하여",    // about
  properties: ["quote"],
});

console.log(searchResult);

// #6
searchResult = search(db, {
  term: "미셸",
  properties: ["author"],
});

console.log(searchResult);
```

Result
```bash
$ node lyrademo.js
{                                                                   // #1
  elapsed: 320018n, hits: [], count: 0 
} 
{                                                                   // #2
  elapsed: 328457n, 
  hits: [
    {
      id: '87050293-2',
      score: 0.11928031367991561,
      document: [Object]
    }
  ],
  count: 1
}
{                                                                   // #3
  elapsed: 53841n,
  hits: [ { id: '87050293-2', score: NaN, document: [Object] } ],
  count: 1
}
{                                                                   // #4
  elapsed: 41796n,
  hits: [
    {
      id: '87050293-2',        // 와 should be either 'wow'  from **1 or 'and' from **2, however we got the result from **1
      score: 0.11928031367991561,
      document: [Object]
    }
  ],
  count: 1
}
{                                                                   // #5 
  elapsed: 30595n, hits: [], count: 0
 }
{                                                                   // #6
  elapsed: 46479n,
  hits: [
    {
      id: '87050293-23',
      score: 0.23856062735983122,
      document: [Object]
    }
  ],
  count: 1
}
```

When I compare the Korean Lyra search with the English one, the Korean search works just like the English search.

Example

`lyra-english.js`

```javascript
// **1
insert(db, {
  quote:
    "It is during our darkest moments that we must focus to see the light.",
  author: "Aristotle",
});

// **2
insert(db, {
  quote:
    "If you really look closely, most overnight successes took a long time.",
  author: "Steve Jobs",
});

// #1
let searchResult = search(db, {
  term: "our",
  properties: "*",
});

console.log(searchResult);

// #2
searchResult = search(db, {
  term: "ou",
  properties: "*",
});

console.log(searchResult);
```

Result
```bash
$node lyra-english.js
  {                                                                   // #1
    elapsed: 1123853n,
    hits: [ 
      { 
        id: '88133009-2',                                             // **1
        score: 0.043004285094854454,
        document: [Object] 
      } 
    ],
    count: 1
  }
  {                                                                   // #2
    elapsed: 88131n,
    hits: [
      {
        id: '88133009-2',                                             // **1
        score: NaN, 
        document: [Object] 
      }
    ],
    count: 1
  }
```
I searched for `our` and `ou` and Lyra only returned the `**1`, which is the same phenomenon as Korean Lyra Search (`#4` example from `lyradeno.js`).

I guess this could be the starting point for the Korean language.

### CODE REVIEW

**Comment by ShogunPanda** [comment]
Hi @tk-425!
First of all, thanks for your submission.
As I'm not familiar with Korean language, can you tell me how `String.split` behaves when applied to the Korean language.
Is it working at single character level or it changes them (like font ligatures, if you understand what I mean)?

**Comment by tk-425** [comment]
Hello @ShogunPanda,
Thank you very much for your interest.
It works at a single character level, meaning a single word, not a consonant or vowel, and doesn't change font ligatures. Korean characters consist of mixed of consonants and vowels. 
For example, "Hello" in Korean is "안녕" and "안녕" is mixed with consonants, "ㅇ" and "ㄴ"  and vowels, "ㅏ" and "ㅕ".
If I want to separate all the consonants and vowels from the word "안녕",  I can write it like this "ㅇㅏㄴㄴㅕㅇ". 
However, the `String.split` function does not separate consonants and vowels when used in the Korean language.
I hope that answers your question. :)

Screenshot
osNYiF3

**Comment by ShogunPanda** [comment]
Thanks @tk-425. I suspected it was the culprit, and same probably goes for similar languages which have complex (and wonderful, if I can) writing systems.
Me and @micheleriva are planning to completely rehaul the hook system of Lyra so that you can replace any predefined step. This way you can hookup your own splitting, tokenizing and stemming libraries and make sure all these languages are properly handled. 

I'll keep you posted here once we do that!

**Comment by micheleriva** [comment]
Closing this due to inactivity

**Pull request closed without merging**
