### PR TITLE
feat: export language with each stemmer

### LINKED ISSUE #510: Indexing of special characters
We have an issue searching for special characters, such as `æ`,`ø` and `å` (Danish letters).

Emojis also seems to cause problems.

```
"@orama/orama": "1.2.10",
"@orama/stemmers": "1.2.10"
```

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fix #510
/claim #510

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
The implementation of `createTokenizer` function did accept stemmer as a whole, but was a exported function and not an object from which language could simply be extracted.

I've added another export to `language` which contains the correct language and can be used with the current props as is. 

Updated the example usage as well.

**Comment by rishi-raj-jain** [comment]
@micheleriva

**Comment by allevo** [comment]
Could you add a test to check if issue #510 is resolved?
Thanks

**Comment by allevo** [comment]
Hi @rishi-raj-jain, could you add a test to check if issue #510 is resolved?
Thanks

**Comment by rishi-raj-jain** [comment]
@allevo @micheleriva I've updated the tests to use the updated import.

**Review by micheleriva — APPROVED** [review]

**Pull request merged**
